import { type ComponentType, lazy } from "react";

export const testContentMap: Record<string, React.LazyExoticComponent<ComponentType>> = {
  headings: lazy(() => import("./headings")),
  images: lazy(() => import("./images")),
  landmarks: lazy(() => import("./landmarks")),
  "tab-order": lazy(() => import("./tab-order")),
  "dark-mode": lazy(() => import("./dark-mode")),
  "reduced-motion": lazy(() => import("./reduced-motion")),
  "inverted-colors": lazy(() => import("./inverted-colors")),
  "reduced-transparency": lazy(() => import("./reduced-transparency")),
  "forced-colors": lazy(() => import("./forced-colors")),
  "video-controls": lazy(() => import("./video-controls")),
  autoplay: lazy(() => import("./autoplay")),
  captions: lazy(() => import("./captions")),
  "audio-description": lazy(() => import("./audio-description")),
  "viewport-zoom": lazy(() => import("./viewport-zoom")),
  language: lazy(() => import("./language")),
  "page-title": lazy(() => import("./page-title")),
  "meta-tags": lazy(() => import("./meta-tags")),
  "form-labels": lazy(() => import("./form-labels")),
  autocomplete: lazy(() => import("./autocomplete")),
  "form-errors": lazy(() => import("./form-errors")),
  "grouped-fields": lazy(() => import("./grouped-fields")),
  links: lazy(() => import("./links")),
  buttons: lazy(() => import("./buttons")),
  "skip-links": lazy(() => import("./skip-links")),
  "new-window-links": lazy(() => import("./new-window-links")),
  aria: lazy(() => import("./aria")),
  "hidden-content": lazy(() => import("./hidden-content")),
  "live-regions": lazy(() => import("./live-regions")),
  "color-contrast": lazy(() => import("./color-contrast")),
  "text-spacing": lazy(() => import("./text-spacing")),
  "touch-target": lazy(() => import("./touch-target")),
  "axe-core": lazy(() => import("./axe-core")),
};
